steps:
  - id: 'npm install'
    name: 'node:20'
    entrypoint: 'npm'
    args: [ 'install' ]
  - id: 'compile emails'
    name: 'node:20'
    entrypoint: 'npm'
    args: [ 'run', 'email:build' ]
  - id: 'npm install functions'
    dir: 'functions'
    name: 'node:20'
    entrypoint: 'npm'
    args: [ 'install' ]
  - id: 'lint'
    dir: 'functions'
    name: 'node:20'
    entrypoint: 'npm'
    args: [ 'run', 'lint' ]
  - id: 'test'
    dir: 'functions'
    name: 'node:20'
    entrypoint: 'npm'
    args: [ 'run', 'test' ]
  - id: 'decrypt secrets'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: [ './scripts/decrypt_secrets.sh', '-e=${_TARGET_ENVIRONMENT}' ]
  - id: 'copy env file'
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'cp'
    args: [ './functions/.env.${_TARGET_ENVIRONMENT}', './functions/.env' ]
  - id: 'firebase deploy'
    name: gcr.io/$PROJECT_ID/firebase
    args: ['deploy', '--only=functions', '--force']